version: "3.3"

services:
  db:
    image: postgres:11
    volumes:
      - bmstu-fun:/var/lib/postgresql/data
    networks:
      - backend

  web:
    image: dchebakov/solver-main
    secrets:
      - bmstu_fun_allowed_hosts
      - bmstu_fun_db_password
      - bmstu_fun_secret_key
    depends_on:
      - db
    networks:
      - backend

  nginx:
    image: dchebakov/solver-nginx
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy:/etc/nginx/deploy
      - ./keys:/etc/nginx/keys
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - backend

volumes:
  bmstu-fun:
    external: true

secrets:
  bmstu_fun_allowed_hosts:
    external: true

  bmstu_fun_db_password:
    external: true

  bmstu_fun_secret_key:
    external: true

networks:
  backend:
