version: "3.3"

services:
  db:
    image: postgres:11
    volumes:
      - bmstu-fun:/var/lib/postgresql/data
    networks:
      - backend

  web:
    image: $MAIN_IMAGE_TAG
    volumes:
      - ./files/media:/app/files/media
    secrets:
      - bmstu_fun_allowed_hosts
      - bmstu_fun_db_password
      - bmstu_fun_secret_key
    depends_on:
      - db
    networks:
      - backend

  nginx:
    image: $NGINX_IMAGE_TAG
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./files/media:/srv/bmstu-fun/files/media
      - ./keys/letsencrypt:/etc/letsencrypt
      - ./keys/conf:/var/www/certbot
    depends_on:
      - web
    networks:
      - backend

volumes:
  bmstu-fun:
    external: true

secrets:
  bmstu_fun_allowed_hosts:
    external: true

  bmstu_fun_db_password:
    external: true

  bmstu_fun_secret_key:
    external: true

networks:
  backend:
